#!/bin/bash

#
# CBRAIN Project
#
# Copyright (C) 2008-2020
# The Royal Institution for the Advancement of Learning
# McGill University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Description here
#

this_script=$(readlink -e "$0" 2>/dev/null)
# On non-linux, "readlink -e" doesn't exist... :-(
if test -z "$this_script" ; then
  this_script="$0"
  if [[ "$this_script" != /* ]] ; then
    this_script="$PWD/$this_script" # good enough
  fi
fi
this_script_dir=$(dirname $this_script)

if test "$#" -lt 6 -o "X$1" != "X-R" -o "X$3" != "X-H" -o "X$5" != "X-D" ; then
  exec "$this_script_dir"/cbrain_remote_ctl_rb "$*"
  exit 10 # should never get here
fi

# Arguments all have a hardcoded index number in this mode.
myhost=$(hostname)
remhost="$2"
httpport="$4"
dbport="$6"
shift 6

umask 077 # for socket access permissions
controlsocket="/tmp/cbrain-login-to-submit.sock"

if test -S $controlsocket ; then
  echo "Found existing master from login host $myhost to backend $remhost"
  if ! ssh -N -o ControlPath=$controlsocket -O check $remhost ; then
    echo "The master seems to be dead, removing socket"
    rm -f $controlsocket
  fi
fi

if ! test -S $controlsocket ; then
  echo "Establishing new master from login host $myhost to backend $remhost"
  ssh -A -f -n -N -x                     \
    -o BatchMode=yes                     \
    -o ControlMaster=yes                 \
    -o ControlPath=$controlsocket        \
    -L ${httpport}:localhost:${httpport} \
    -R ${dbport}:localhost:${dbport}     \
    -p 22                                \
    $remhost

  ssh_status=$?
  if $ssh_status -gt 0 ; then
    echo "Could not start SSH master: status $ssh_status" 1>&2
    exit $ssh_status
  fi
fi

ssh -o ControlPath=$controlsocket $remhost \
  "cd \"$this_script_dir\"; bundle exec ruby \"$this_script\" $@ 2>&1" # will read from STDIN too

if test "X$1" = "Xstop" ; then
  echo "Stopping master from login host $myhost to backend $remhost"
  ssh -N -o ControlPath=$controlsocket -O exit $remhost # this is nice, this -O option for controlling the master
fi

