#!/usr/bin/env ruby

#
# CBRAIN Project
#
# Copyright (C) 2008-2012
# The Royal Institution for the Advancement of Learning
# McGill University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Pure ruby, no rails or active support

# Only one option, "-z" means to default to "0.1.0" if no tags found
default_tag = (ARGV.size == 1 && ARGV[0] == "-z") ? "0.1.0" : nil

top = `git rev-parse --show-toplevel`.chomp
if top.nil? || top =~ /^\s*$/
  STDERR.puts "Cannot find GIT top level directory? Please CD to somewhere within the CBRAIN code base."
  Kernel.exit(10)
end

# Code lifted almost as-is from cbrain_file_revision.rb

    Dir.chdir(top) do
      out = `git describe --tags --long`
      if out
        git_tag = out.rpartition('-')[0]
                     .chomp('-0')
        puts git_tag
        Kernel.exit(0)
      end
    end

STDERR.puts "Cannot find GIT tags?!?"
Kernel.exit(10)

