#!/usr/bin/env ruby

# Pure ruby, no rails or active support

top = `git rev-parse --show-toplevel`.chomp
if top.nil? || top =~ /^\s*$/
  STDERR.puts "Cannot find GIT top level directory? Please CD to somewhere within the CBRAIN code base."
  Kernel.exit(10)
end

# Code lifted almost as-is from cbrain_file_revision.rb

    git_tag = nil
    seen    = {}
    Dir.chdir(top) do
      tags_set = `git tag -l`.split # initial list: all tags we can find
      git_tag = tags_set.shift unless tags_set.empty? # extract one as a starting point
      seen[git_tag]=true
      while tags_set.size > 0
        tags_set = `git tag --contains '#{git_tag}'`.split.sort.reject { |v| seen[v] }
        git_tag = tags_set.shift unless tags_set.empty? # new first
        seen[git_tag]=true
      end
      if git_tag
        num_new_commits = `git rev-list '#{git_tag}..HEAD'`.split.size
        git_tag += "-#{num_new_commits}" if num_new_commits > 0
        puts git_tag
        Kernel.exit(0)
      end
    end

STDERR.puts "Cannot find GIT tags?!?"
Kernel.exit(10)

