# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# CBRAIN special notes: on the Bourreau app side, there
# are no cookies or secrets to maintain, because there are
# no sessions, so none of the token below need to be provided
# or adjusted. However, they still need a dummy value for the
# Rack to start.
#
# See also this comment from March 2022 about this:
#
# https://stackoverflow.com/questions/33909022/rails-disabling-secrets-yml-for-api
#
# Once the framework has a proper way to disable these secrets,
# we can safely remove this file.

development:
  secret_key_base: NOT-USED-IN-BOURREAU

test:
  secret_key_base: NOT-USED-IN-BOURREAU

production:
  secret_key_base: NOT-USED-IN-BOURREAU
