# The data generated by this file is extracted from the sibling 'in.json' file

CbrainClient::MultiUserfilesModReq.new(
  :file_ids                   => read_local_json("file_ids").first,
  :data_provider_id_for_mv_cp => read_local_json("data_provider_id_for_mv_cp").first,
)

