source 'http://rubygems.org'

gem 'rails', '3.0.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end

gem "net-ssh",  :require => 'net/ssh'
gem "net-sftp", :require => 'net/sftp'
gem "will_paginate"
gem "log4r"
gem "nokogiri"
gem "mysql"
gem "sys-proctable", :git => 'git://github.com/djberg96/sys-proctable.git'
#gem "sys-proctable", "~> 0.7.6"
gem "thin"
gem "exception_logger", "~> 0.1.10"

group :development do
  gem "wirble"
  gem "looksee"
  gem "hirb"
end

group :test do
  gem "test-unit"
  gem "rspec"
  gem "rspec-rails"
  gem "factory_girl"
end

