
#
# CBRAIN Project
#
# Copyright (C) 2008-2012
# The Royal Institution for the Advancement of Learning
# McGill University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

source 'http://rubygems.org'

# In the :default group
gem 'rails',    :git => 'https://github.com/rails/rails.git', :branch => "3-2-stable"
gem 'aws-s3',   :require => 'aws/s3' # Client library for Amazon's Simple Storage Service's REST API
gem "net-ssh",  :require => 'net/ssh'
gem "net-sftp", :require => 'net/sftp'
gem "log4r"
gem "mysql2"
gem "sys-proctable", :git => 'git://github.com/djberg96/sys-proctable.git'
gem "thin"
gem "pbkdf2-ruby"
gem "json-schema"

group :development, :test do
  gem "wirble"
  gem "looksee"
  gem "hirb"
end

