
#
# CBRAIN Project
#
# Copyright (C) 2008-2012
# The Royal Institution for the Advancement of Learning
# McGill University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

source 'https://rubygems.org'

# In the :default group
gem 'rails', '~> 5.0.6'
gem "net-ssh",       :require => 'net/ssh'
gem "net-sftp",      :require => 'net/sftp'
gem "sys-proctable", '~> 1.2.0'
gem "mysql2"
gem "log4r"
gem "puma"
gem "pbkdf2-ruby"
gem "json-schema"
gem "aws-sdk", '<2.0'

# ActiveResource channel gems
gem "activeresource", require: 'active_resource'
gem "actionpack-xml_parser"
gem "activemodel-serializers-xml"

group :development do
  gem "wirble"
  gem "looksee"
  gem "hirb"
  gem "pry"
  gem "pry-byebug"
  gem "listen", '~> 3.0.5'
end

group :test do
  gem "rspec"
  gem "rspec-rails"
  gem "factory_bot_rails", :require => false
  gem "rails-controller-testing"
  gem "rspec-mocks"
  gem "rspec-activemodel-mocks"
  gem "rspec-collection_matchers"
  gem "database_cleaner"
end

